### ISSUE TITLE
jcr:createdBy value not displaying in asset detail page

### ISSUE THREAD

**Issue by RahulMohann** [adobe/asset-share-commons#1012]
Hi,

We need to display the created user info in the detail page. For that, we have mapped jcr:createdBy property to a metadata property in the asset detail page. In author, it's showing the user name. But when published, it's displaying 'sling-distribution-importer' instead of the actual user name/email. Could you please help on how to resolve this? Any permission missing?

Thanks,
Rahul

**Comment by davidjgonzalez** [comment]
@RahulMohann hi - sorry for the delay - i was out of town.

This sounds like something to investigate with AEM rather than ASC, since ASC has nothing to do w/ how this value is set.

Assuming you receive feedback from Adobe Support that this is the expected value on AEM Publish, I expect youll need to create a custom AEM Author workflow that copies the `jcr:createdBy` value to a custom property on the asset ex (`myApp:createdBy` or whatever you want to call the property). Depending on ehwat you want to show, you may want to copy more human friendly user info over as well -- for example, if your user ID's are email address, you could use this WF to look up the first/last name on AEM Author for that user, and copy that into `myApp:createdByFullName` and also display that incase ppl havent memorized emails (and its very possible all your authors will have accounts on AEM Publish, so you wont be able to look them up "on render")

Here's some info on how to create a custom namespace in AEM if you end up wanting to go down that route:

https://experienceleague.adobe.com/docs/experience-manager-learn/cloud-service/developing/advanced/custom-namespaces.html?lang=en

Please re-open if you have more Qs on this!

**Comment by RahulMohann** [comment]
Hi @davidjgonzalez , 
Thanks for the update. I've tried using the available workflow process step - 'Copy Properties' , which I think is part of acs commons. But it's not working as expected. This is the property mapping I've given in the workflow step 
 - ./jcr:createdBy => ./jcr:content/metadata/dam:uploadedby . 

I'm getting workflow failure with message - com.adobe.granite.workflow.WorkflowException: Process resource is null.

Could you please let me know if there is anything wrong in this?

Thanks,
Rahul

**Comment by davidjgonzalez** [comment]
What version of acs commons?
What line is that exception on?
And how are you tying that wf process step in the wf? (Which wf and how is it triggered)

This is saying the workflow engine is passing a null resource to the workflow model, which is strange.

**Comment by RahulMohann** [comment]
**ACS commons version is 5.6.0.**

**What I've done -**
1) Created a new workflow model.
2) Added a process step - 'Copy Properties' with argument './jcr:createdBy -> ./jcr:content/metadata/dam:uploadedby'
3) Synced the workflow.
4) Started the workflow - pointed to an asset as payload that have these fields in its metadata.
5) Workflow failed.

**Complete exception:**

com.adobe.granite.workflow.WorkflowException: Process resource is null
	at com.adobe.granite.workflow.core.job.HandlerBase.executeProcess(HandlerBase.java:134)
	at com.adobe.granite.workflow.core.job.JobHandler.process(JobHandler.java:300)
	at org.apache.sling.event.impl.jobs.JobConsumerManager$JobConsumerWrapper.process(JobConsumerManager.java:502)
	at org.apache.sling.event.impl.jobs.queues.JobQueueImpl.startJob(JobQueueImpl.java:351)
	at org.apache.sling.event.impl.jobs.queues.JobQueueImpl.access$100(JobQueueImpl.java:60)
	at org.apache.sling.event.impl.jobs.queues.JobQueueImpl$1.run(JobQueueImpl.java:287)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by davidjgonzalez** [comment]
so, based on this stacktrace this is a product issue (you can see there are no ASC or ACS commons package sin the stacktrace). 

This makes me think:
1. You started the WF Model on the payload incorrectly (how exactly did you do this?)
2. There's a bug in AEM, which seems unlikely for something like this.

**Comment by RahulMohann** [comment]
![image](https://github.com/adobe/asset-share-commons/assets/99810531/865bc9e3-b54a-436a-b625-70eaea6b1642)
![image](https://github.com/adobe/asset-share-commons/assets/99810531/1eb1beee-999b-4029-a551-98d01b37d43c)
![image](https://github.com/adobe/asset-share-commons/assets/99810531/b00f8c4b-72c7-4f91-9fb8-ed5f47e6b2d1)
![image](https://github.com/adobe/asset-share-commons/assets/99810531/a70a9802-7d6b-4e8d-a077-297e167f9923)

**Comment by RahulMohann** [comment]
Hi @davidjgonzalez ,

Just uploaded few screenshots if that helps. Or if you need, I can share the workflow model as well. Thanks for your support.

Thanks,
Rahul

**Comment by RahulMohann** [comment]
Hi @davidjgonzalez ,

Any idea why this is happening.

Thanks,
Rahul

**Comment by davidjgonzalez** [comment]
@RahulMohann nope - can you try starting that WF Model

1. without the custom WF Process step
2. With a WF process step, but pick one of the OOTB ones

If if has the same error with 1 or 2 then it sounds like there's an issue in AEM we cant fix.
If this only effects the ACS Commons WF process, then we could look to fix it there - tho im skeptical of this since i dont see any ACS packages in the error stack strace.

**Comment by RahulMohann** [comment]
Hi @davidjgonzalez ,

I tried the below two steps.

1. without the custom WF Process step --> Worked fine.
2. With a WF process step, but pick one of the OOTB ones --> Worked fine.

I'm just sharing the argument I'm giving for the copy properties process step. Hope this is the correct format?
./jcr:createdBy -> ./jcr:content/metadata/dam:uploadedby

Thanks,
Rahul

**Comment by RahulMohann** [comment]
Hi @davidjgonzalez , A gentle reminder. Any update to share? Or do I need to write a custom process to copy the value from createdby property to my custom field?

Thanks,
Rahul

**Comment by davidjgonzalez** [comment]
@RahulMohann i recommend writing your own - im not sure why your AEM isnt processing a custom WF process -- the stacktrace doesnt seem to invoke any of the custom code so im at a loss. Sorry!
