### ISSUE TITLE
search with multiple filters doen't respond when iterated multiple times

### ISSUE THREAD

**Issue by sayabannatole** [adobe/asset-share-commons#1016]
Hi Team,

We are using the asset share commons 1.9.4. Observed that filter component doesn't respond when we have multiple filter options inlvolved and search is done on that.
Ex: When we select multiple filters like expiry date, categories and use some keyword to search and seacrh returns results
next we change the selection in category and serch with existing keyword and search returns the results
When we change the keyword in third iteration and click on filter, it doesn't respond.
After refresh of page the filter option starts to respond.

Can you please let's know if this is observed by anyone else using the asset share commons.?

Thanks,
Sayabanna

Documentation can be found here: https://opensource.adobe.com/asset-share-commons/. It might answer your question!

**Comment by davidjgonzalez** [comment]
@sayabannatole can you reproduce here: https://aem.enablementadobe.com/content/asset-share-commons/en/light.html ?

Also, v1.9.4 is quite old (Jul 26, 2021) -- would it possible to upgrade to a newer version of ASC? There have been many bug fixes and improvements since then.

On 1.9.4 do you see any errors in your JS console at all when you go through your search sequence? Also, after each change in search filtering, do you see your browser address bar change? It should update based on current set of search criteria.

**Comment by sayabannatole** [comment]
Hi @davidjgonzalez,

I tried to reproduce the issue in the shaed link but it works fine there.
in the JS console of our instance Asset share we don't see any error reported from search or result components.
The address bar changes till the iteration two with search text and the filters applied. 
At iteration 3 the address bar remains as the apply filter button doesn't trigger the event to update the search.

Thanks

**Comment by davidjgonzalez** [comment]
Were you able to figure anything out w/ this?

**Comment by davidjgonzalez** [comment]
please re-open w more details if you still ave this problem
