### ISSUE TITLE
Asset-share-common 3.3.0 content-package dont have the ASC site 

### ISSUE THREAD

**Issue by madhuch28** [adobe/asset-share-commons#1051]
Asset-share-common 3.3.0 content-package doesnt have the ASC site i.e. /content/asset-share-common & /dam folders.

We are upgrading ASC code from 1.9.4 version to latest 3.3.0 , currently we are using SP 17 so integrated ( ui.apps , core , ui.content , ui.frontend.light and ui.config ) modules and build is good and bundle is active. However, we are unable to view "asset-share-commons" site in AEM author instance.
verified the [assetshare.all-3.3.0.zip](https://github.com/adobe/asset-share-commons/releases/download/asset-share-commons-3.3.0/assetshare.all-3.3.0.zip) and this package so doesnt contain the site package with "/content" and "/dam" folder.

![image](https://github.com/adobe/asset-share-commons/assets/149188199/62a98eb4-d750-4a6f-ac72-25204c638341)

Q:
1. Do we need to copy the folder structure from ui.content-sample package to ui.content 
1. Do need to author AEM site by adding the components ?

**Comment by davidjgonzalez** [comment]
Hi @madhuch28 - thats correct. the ui.content page in "all" only has `/conf/asset-share-commons` since `/content/dam/asset-share-commons` and `/content/asset-share-commons` are just samples. 

The intent was you could create your own /content structures, like `/content/acme-asset-share` .. or whatever you want to name your asset share. You can copy structures out of `ui.sample.content` if you want - and keep them as is, or use them as the base of your own content.

Please re-open if this doesnt clarify!

**Comment by madhuch28** [comment]
@davidjgonzalez Thanks for the clarification.
So if we want to use ui.sample.content as the base then we can use this as the "content" package instead of ui.content ? and do we need to update any package dependencies ?
