### ISSUE TITLE
"Page Policy" tempate configuration option is missing

### ISSUE THREAD

**Issue by artdirk** [adobe/asset-share-commons#192]
I don't know if anyone else has encountered this issue, but when I deployed the Asset Share Commons 1.5.0 release into my local AEM 6.4 instance I noticed that the "Page Policy" template configuration option was missing from the Asset Share templates.

I opened a ticket with AMS, and the fix they suggested was changing the "sling:resourceSuperType" property to "core/wcm/components/page/v2/page" (from "core/wcm/components/page/v1/page") on the /apps/asset-share-commons/components/structure/page component.

This solved my issue, and AMS suggested bringing it to your attention. Thanks!

**Comment by godanny86** [comment]
Thanks @artdirk for letting us know. On your local instance what version of Core Components is installed (I think default installation for 6.4 will be 2.0.4?). Asset Share Commons is set up to use 1.1.0 but in Core Components is supposed to be backwards compatible. I'm curious if you can reproduce this when running AEM 6.4 in production nosamplecontent mode?

Instead of changing the `sling:resourceSuperType` a safer approach would be to copy the design dialog from `/libs/wcm/foundation/components/basicpage/v1/basicpage/cq:design_dialog` beneath the page component.

**Comment by davidjgonzalez** [comment]
Fixed in 2.0.0 with bump to v2 Page component
