### ISSUE TITLE
Change ThumbnailImpl to use the Thumbnail servlet instead of the 319x319 rendition

### ISSUE THREAD

**Issue by kaushalmall** [adobe/asset-share-commons#223]
**Is your feature request related to a problem? Please describe.**
Not a problem, but can potentially be a problem. Currently the ThumbnailImpl class uses the `cq5dam.thumbnail.319.319.png` rendition to display in the search results component. This results in a img src as `/content/dam/myasset.jpg/_jcr_content/renditions/cq5dam.thumbnail.319.319.png`. This path can potentially become a problem when caching on the dispatcher since it'll create the myasset.jpg as a folder. 

**Describe the solution you'd like**
In the ThumbnailImpl class, we can use the `thumb` selector, so the img src becomes something like `/content/dam/myasset.jpg.thumb.319.319.png`

**Comment by davidjgonzalez** [comment]
Using the OOTB servlet, the missing image placeholder is automatically used; but then we should remove the custom missing placeholder image.... or perform some logic that checks if 319/319 exists and if not, then returns null, else the servlet path?

I actually like just using the OOTB servlet as it simplifies everything (less config, less code, etc.)  but there are some other considerations.
 
![image](https://user-images.githubusercontent.com/1451868/44799341-ae684500-ab81-11e8-854d-26a382912b72.png)

**Comment by kaushalmall** [comment]
@davidjgonzalez need to look at the code again, but how do we end up with the screenshot above instead of the 319x319 rendition for the assets?

**Comment by davidjgonzalez** [comment]
By doing what you suggest. The screenshot above uses the aem OOTB missing thumbs image vs. the ASC missing placeholder images. If the 319x319 rendition existed for the assets above, hey would be used, but since they are 0 byte binaries, they of course don’t have renditions, this the AEM OOTB placeholder by way of the OOTB thumb servlet

**Comment by kaushalmall** [comment]
Thanks, @davidjgonzalez makes sense. Only if the OOTB servlet provided a way to configure the default thumbnail....

Can we just leave it like this and drop the default thumbnail feature?

**Comment by davidjgonzalez** [comment]
Seems reasonable to me - but maybe leave ~ old code that can be toggled on via osgi config? (Maybe move that path into config and remove from page props?)

I’d hate to rip out func completely Incase someone does like/use it

**Comment by kaushalmall** [comment]
agreed. want me to work on it? push your branch?

**Comment by davidjgonzalez** [comment]
Sure - go for it, either way.

It might be nice to update current logic to still use the thumb 319 319 servlet IF That rendition exists rather than using the full rendition url (which as you call out in the original issue is an anti pattern)

**Comment by rakeshkonda** [comment]
Instead of thumb rendition, is there a way to get web rendition?

**Comment by khanaaqib** [comment]
I have created audio component in ASC and everything is working fine but i am able to get the thumbnail image.Is there anyway that we can fix it. PFB Screen-Shot
![image](https://user-images.githubusercontent.com/35225284/82786192-c6b5e280-9e81-11ea-8280-a3c49ee8c829.png)

**Comment by davidjgonzalez** [comment]
@rakeshkonda you should be able to register an "asset rendition" that maps to any static rendition: https://adobe-marketing-cloud.github.io/asset-share-commons/pages/development/asset-renditions/ and then use that. You could even create a mapping w/ a higher service ranking than the OOTB and use the .card. and .list. selectors!

**Comment by davidjgonzalez** [comment]
@khanaaqib can you provide a screenshot of those renditions in the AEM Assets author UI so we can see wht they should be? Those are audio files, so im not sure what you're expecting as thumbnails.

**Comment by khanaaqib** [comment]
Hi @davidjgonzalez PFB screenshot of audio(.mp3) file.
![image](https://user-images.githubusercontent.com/35225284/82982651-3fe14100-a00c-11ea-9faf-64f44aee1854.png)
see here there is no rendition is present instead of original.
PFB screenshot of video file.
![image](https://user-images.githubusercontent.com/35225284/82982814-99e20680-a00c-11ea-83a1-28a89ea3d98c.png)
see here along with original renditions there is other thumbnail images is present but in audio file by default there is no thumbnail  is present.I don't want to do it manually,like copy thumbnail to the other file and paste it here it is working fine by doing this but i don't want to do this(manually) like that.
when i developed audio component in home page it is appear in following way.PFB Screenshot.
![image](https://user-images.githubusercontent.com/35225284/82983732-4375c780-a00e-11ea-900e-67ef39f91ed0.png)
see here no thumbnail images is present in audio file.
But in Video file thumbnail images is present.PFB screenshot.
![image](https://user-images.githubusercontent.com/35225284/82983987-d0208580-a00e-11ea-88a1-61d7c1f1ffdc.png).
I think you got some idea what i am looking for.Please help me how can i do this to get the desired output.

**Comment by davidjgonzalez** [comment]
This is in 1.9.6 or 2.x
