### ISSUE TITLE
Issue with context hub 

### ISSUE THREAD

**Issue by preetsekhon94** [adobe/asset-share-commons#468]
Hi,

We are facing issue while loading context hub in Asset share. We are getting console issues that profile pic is missing for logged in user.
Please refer below errors:

1. Resource at '/home/users/h/hDL___ts9Wul2bDObSGQ/profile/photos/primary/image.prof.thumbnail.128.128.png' not found: No resource found
Cannot serve request to /home/users/h/hDL___ts9Wul2bDObSGQ/profile/photos/primary/image.prof.thumbnail.128.128.png on this server

2. Uncaught SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Object.success (clientlib-base.js:2017)
    at fire (clientlib-dependencies.js:3233)
    at Object.fireWith [as resolveWith] (clientlib-dependencies.js:3363)
    at done (clientlib-dependencies.js:9841)
    at XMLHttpRequest.callback (clientlib-dependencies.js:10312)

**Comment by davidjgonzalez** [comment]
@preetsekhon94 what version of AEM are you using?

Do note that if you dont have a profile pic, the request for it will 404.. this isnt an error persay, since the user simply doesnt have a profile pic (a 404 isnt necessarily a problem; its only a problem if you EXPECT the resource to be there and it isnt)

**Comment by Blaris** [comment]
This is actually fixed by doing the following: 

is to change this file: /libs/cq/personalization/components/target/engine_cq.jsp

Look for this comment: (Line 109 in 6.5.8)
// Make the targeted content visible if no teasers were loaded after 5s

and change it to: 

/* Make the targeted content visible if no teasers were loaded after 5s */

Then Replicate.  If replication does not work, use the package manager to move the file to the publishers.

**Comment by davidjgonzalez** [comment]
@Blaris just to be clear, you should never change anything under `/libs` ... `/libs` is the domain of the product, and the only thing youre allowed to "do" there is add ACLs if needed. You also need to make sure you respect the content classifications [1] even if youre going to overlay something there in `/apps`.

https://experienceleague.adobe.com/docs/experience-manager-64/deploying/upgrading/sustainable-upgrades.html?lang=en#content-classifications

**Comment by Blaris** [comment]
Correct, we are not changing any functionality of the file itself. Simply correcting a syntax error that causes issues when it is compiled. We chose to do it this way so that when/if it changes, we inherit those changes.
