### ISSUE TITLE
Component exporters overwrite default exporters for components without sling:resourceSuperType and breaks SPA framework

### ISSUE THREAD

**Issue by AlexLumo** [adobe/asset-share-commons#674]
**Describe the bug**
Asset-share commons overwrite default component exporters for components that don't have sling:resouceSuperType property or custom JSON exporter. This causes AEM SPA framework to render wrong components

**Environment**
* AEM Version: 6.5.11
* Asset Share Commons Version: 2.1.12
* Author, Publish or both? Both

**To Reproduce**
1. Download and install SPA example project https://github.com/adobe/aem-sample-we-retail-journal/releases/tag/we-retail-journal-1.2.4
2. Install Asset-share-commons
3. Open exporter URL: http://localhost:4502/content/we-retail-journal/react/en.model.json
4. Observe that there are entries with "asset-share-commons/components"

**Expected behavior**
Page exporters should not override default exporters

**Screenshots**
![image](https://user-images.githubusercontent.com/17319740/145220702-7b1d0d6a-484f-4b0e-a82d-9f33914cb902.png)

**Additional context**
Problem is caused by redundant ComponentExporter adapter in @Model annotation

**Comment by godanny86** [comment]
@AlexLumo I have seen this behavior before but only for nodes without a `sling:resourceType` i.e just a plain old `nt:unstructured` node. Are you observing nodes **with** a `sling:resourceType` being overwritten? 

FWIW this isn't just an Asset Share Commons issue but potentially any application that chooses to use the Component Exporter since as a fall back I think the first model gets picked up alphabetically [0].

https://sling.apache.org/documentation/bundles/models.html#specifying-an-alternate-adapter-class-since-110

**Comment by AlexLumo** [comment]
@godanny86 yeah, this issue reproduces for all components that don't have component exporter set explicitly i.e. component doesn't have sling:resourceSuperType and Java class to serialize its properties. In this case we are expecting to see just node properties in resulting JSON, but those properties are replaced with one of the model from ASC.

For instance, in Exported page model instead of this:
```
{
    "id": "text-4cd13a52d9",
    "text": "<p>Some text</p>",
    "richText": true,
    ":type": "we-retail-journal/components/somecustomcomponentwoexporter"
}
```
we receive this:
```
{
    "assets": [],
    "paths": [],
    ":type": "asset-share-commons/components/modals/cart"
}
```

**Comment by godanny86** [comment]
yeah, its definitely a shortcoming of the component exporter framework. `com.adobe.cq.export.json.impl.FallbackComponentImpl` was created to deal with components which don't implement a Component Exporter interface but I think it fools us into thinking its working because `com.adobe.cq.export.` tends to be the first alphabetically (over `com.adobe.cq.wcm.` or `com.adobe.cq.sample`) until you introduce something like `com.adobe.aem.commons.assetshare`. But ripping out the exporter from ASC really isn't a general solution.

Ideally there is a more productized way but in the interim I see two approaches:

1. Ensure that each component is backed by a Sling Model that implements the Component Exporter (or via a sling:resouceSuperType). Probably a best practice.

2. Or if the above is too cumbersome (especially if you just want the content properties to dumped and have no extra business logic) implement I think you could implement your own implementation picker and force the `com.adobe.cq.export.json.impl.FallbackComponentImpl` to be chosen. Check out this gist: https://gist.github.com/godanny86/2b40dd7b91aad8504d9631db1808fa18

@davidjgonzalez or @justinedelson might have better ideas.

**Comment by AlexLumo** [comment]
@godanny86 I'm just curious, what is the reason of adding `ComponentExporter` adapter to all models in ASC library if JSON exporters work even without this adapter?

**Comment by godanny86** [comment]
>  if JSON exporters work even without this adapter

The fallback impl just seralizes the jcr properties for the component under `/content`. While adding the `ComponentExporter` will serialize methods in the implementing Sling Model. This would be important for cases like Asset Share commons where the components don't contain any real "content" and instead use the url suffix to expose data about an image/video etc... Think of the Asset Detail components.

**Comment by godanny86** [comment]
however to your earlier point, the component exporter doesnt quite work in ASC and isnt used. However I'd like to leave the option open in the future to better implement :)

**Comment by davidjgonzalez** [comment]
Neither here nor there, but here's a POC branch that got ASC starting to generate SPA-editor usable `model.json`

https://github.com/davidjgonzalez/asset-share-commons/commit/7fdf0677725b1c053cd496e194cd8d11ce52e562


IIRC the way the .model.json serialization works, is it walks the cq:Page tree's subnodes, and for each resources it tries to adapt that resource using its resourceType to a ComponentExporter object; which is why you need to specify ComponentExporter.class as the adapter. If you don't then it uses the Fallback to do a "dumb"  property-based serialization of the resource, rather than serializing the Sling Model representation OF the resource. Of course, ASC would require model-based serialization since much of the important component info is derived in sling model logic.

That said, it seems weird/wrong that the "first" ComponentExporter would be picked if no model is explicitly mapped to that resource's type; youd think that the Fallback would be "force invoked", rather than picking the first one (which is essentially random for all practical purposes)

**Comment by AlexLumo** [comment]
@davidjgonzalez gotcha, thanks for en explanation. But why do we need ComponentExporter adapter in models, if they are serialized correctly even without it? From the documentation I see the following: https://sling.apache.org/documentation/bundles/models.html#exporter-framework-since-130-1
```
@Model(adaptable = Resource.class, resourceType = "myco/components/foo")
@Exporter(name = "jackson", extensions = "json")
```
No need to specify adapter at all

**Comment by godanny86** [comment]
I don't think the models get serialized correctly without ComponentExporter if the model/component extends another component (which ASC components does for many of the Core components)

That aside, I saw similar behavior with another project last month that was deploying a SPA Editor and CIF Core Components [0] to the same environment and ran into the same issue you are seeing. Where `com.adobe.cq.commerce.core.components.internal.models.v2.teaser` took precedence over `com.adobe.cq.export.json.impl.FallbackComponentImpl` based on the package name. 

Have you experimented with using a CustomImplementationPicker [1] ? I think this will give you more control and is a more scalable solution...

[0] - https://github.com/adobe/aem-core-cif-components 
[1] - https://gist.github.com/godanny86/2b40dd7b91aad8504d9631db1808fa18

**Comment by AlexLumo** [comment]
Thanks @godanny86, this makes sense :)
