### ISSUE TITLE
WKND example project using Asset Share Commons (wknd-asset-share.all-1.0.0-SNAPSHOT.zip) brakes AEM

### ISSUE THREAD

**Issue by manuelSanchezYague** [adobe/asset-share-commons#702]
**Describe the bug**
Hi! If I start a new author SDK and upload certain packages and close the AEM instance, if I try to start it again, it crashes with the following error message: "HTTP ERROR 503 AuthenticationSupport service missing. Cannot authenticate request."

**Environment**
* AEM Version: aem-sdk-2022.2.6276.20220205T222203Z-220100 (I believe it can happen with the latest one too)
* Asset Share Commons Version: v.2.1.12
* Author, Publish or both? Author

**To Reproduce**
1. Start a brand new AEM author SDK instance
2. Go to http://localhost:4502/crx/packmgr/index.jsp
3. Upload and install at least the following packages:
3.1. asset-share-commons.all-2.1.12.zip
3.2. wknd-asset-share.all-1.0.0-SNAPSHOT.zip
4. Stop the Author instance
5. Start it again
6. You should see the following message: "HTTP ERROR 503 AuthenticationSupport service missing. Cannot authenticate request."
7. If you check the error.log, you should see the following messages:
"07.03.2022 09:56:08.826 *INFO* [sling-default-6-health-com.adobe.granite.queries.impl.hc.QueriesStatusHealthCheck] com.adobe.granite.queries.impl.hc.QueriesStatusHealthCheck Could not retrieve QueryStats MBean.
07.03.2022 09:57:00.267 *ERROR* [qtp1266288219-75] org.apache.sling.engine.impl.SlingHttpContext handleSecurity: AuthenticationSupport service missing. Cannot authenticate request."
8. I have also tested this problem installing the following packages:
8.1. aem-guides-wknd.all-1.1.0.zip
8.2. asset-share-commons.all-2.1.12.zip
8.3. asset-share-commons.ui.content.sample-2.1.12.zip
8.4. wknd-asset-share.all-1.0.0-SNAPSHOT.zip

**Expected behavior**
After deploying the WKND Asset Share Commons sample project I should be capable of still using the SDK normally even the next day.

**Comment by davidjgonzalez** [comment]
@manuelSanchezYague - can you post the `wknd-asset-share.all-1.0.0-SNAPSHOT.zip` youre using? 

I tried just using

+ aem-sdk-2022.2.6433.20220223T194056Z-220100 
+ ASC 2.20

And it works fine at least - so im guessing its something in the wknd-asset-share (also, are you sure wknd-asset-share-all doenst contain a version of ASC already, meaning you wouldnt deploy your own?)

**Comment by manuelSanchezYague** [comment]
Hi!

I got it from here: https://github.com/godanny86/wknd-asset-share/releases/tag/1.0.0-SNAPSHOT 
I arrived to that page from https://opensource.adobe.com/asset-share-commons/pages/getting-started/new-project/ (at the bottom)

I have not checked what wknd-asset-share-all contains. I was just trying to determine which zip was destroying my SDK and I was trying some combinations
[wknd-asset-share.all-1.0.0-SNAPSHOT.zip](https://github.com/adobe/asset-share-commons/files/8198949/wknd-asset-share.all-1.0.0-SNAPSHOT.zip)

Thanks for your help.

**Comment by davidjgonzalez** [comment]
@manuelSanchezYague - Hi - i think there's an issue with the RepoInit scripts in that, that prevent AEM from starting up (since it re-evals Repo init scripts on startup).

Also, that package includes a version of ASC (v2.1.10) and then you're providing another version (v2.1.12) - which will likely conflict since theyre both full-releases (not SNAPsHOTS) -- so you want to make sure you only isntall 1 version of ASC at a time.

Can you try installing:

1. The latest ASC All package (available for download under GH releases)
2. The 2 wknd-asset-share packages i pulled out of the larger package, and see if these 3 together work for you?

[wknd-asset-share.ui.apps-1.0.0-SNAPSHOT.zip](https://github.com/adobe/asset-share-commons/files/8206918/wknd-asset-share.ui.apps-1.0.0-SNAPSHOT.zip)
[wknd-asset-share.ui.content-1.0.0-SNAPSHOT.zip](https://github.com/adobe/asset-share-commons/files/8206919/wknd-asset-share.ui.content-1.0.0-SNAPSHOT.zip)

**Comment by manuelSanchezYague** [comment]
Thanks a lot. I will try it right now!

**Comment by manuelSanchezYague** [comment]
Hi again @davidjgonzalez !

I have tested that the packages you provided me work with asset-share-commons.all-2.2.0.zip and the WKND project without a problem. I can now restart my AEM normally.

Thanks a lot for helping me and for telling me what was happening.

**Comment by davidjgonzalez** [comment]
Great news!! Thanks!
