### ISSUE TITLE
Search results component issue

### ISSUE THREAD

**Issue by apoorvvermarics** [adobe/asset-share-commons#716]
### Expected Behaviour
While searching for pdf keyword or any pdf document using my AEM author credentials I can see the link having document.html page in there. Please see the bottom of the screenshot for the URL which comes on hover.

However while using someone else credentials I see different page comes for same asset in the search list. I am not able to figure out why 2 different pages coming for 2 different users.
Please see attached screenshots.

Not sure where to attach screenshot.

**Comment by godanny86** [comment]
hi @apoorvvermarics see issue #714 . It is a permission error because the lookup to evaluate the Asset Type is based on a node structure that is protected  under /libs. I'm working on a fix.

A couple of workarounds in the mean time, you could add an ACL to make the path `/libs/dam/gui/content/assets/jcr:content/mimeTypeLookup` readable by everyone. Or you could implement a new Computed Property [0] that removes the need for this lookup node. Implementing a computed property is probably preferable. 

[0] https://opensource.adobe.com/asset-share-commons/pages/development/computed-properties/

**Comment by davidjgonzalez** [comment]
Assigning to myself and mapping to https://github.com/adobe/asset-share-commons/pull/719

Well decide if went to include PR 719 as we evaluate danny's newer approach described in #714
