### ISSUE TITLE
Issue while retrieving collections in publish page of ASC

### ISSUE THREAD

**Issue by Jaski96** [adobe/asset-share-commons#728]
Hi, We are trying to access collections via filters in our ASC page. It works fine in our author page but on publish page it is coming as blank. Please suggest a fix for the same.
![image](https://user-images.githubusercontent.com/105772836/169829656-066082f1-6caf-4c28-9588-b6e3fcafec45.png)

**Comment by davidjgonzalez** [comment]
How are you publishing collections to AEM Publish? And have you verified that they are permissioned correctly?

ASC doesn't have any native Collections support persay, because there is no OOTB to publish Collections from AEM Author to AEM Publish.  Ill close this issue because of this, but happy to brainstorm what you could do from a custom code POV to support this use case. If you do figure out a way to replicate Collections, the OOTB AEM Collections QueryBuilder predicate should work just fine w/ ASC (via a custom filter component)
