### ISSUE TITLE
Searching with a leading space never returns a result

### ISSUE THREAD

**Issue by kwin** [adobe/asset-share-commons#741]
In case you search for ` adam` (notice the leading space, https://aem.enablementadobe.com/content/asset-share-commons/en/light.html?fulltext=+adam&orderby=%40jcr%3Acontent%2Fjcr%3AlastModified&orderby.sort=desc&layout=card&p.offset=0&p.limit=0) you never get any result, while both `adam` and `adam ` return a result.

As the leading space should be considered a typo the fulltext parameter should be trimmed (https://docs.oracle.com/javase/8/docs/api/java/lang/String.html#trim--) before being used. One can still use `" adam"` if one intends to explicitly look for the leading space.

**Comment by DigiLiviu** [comment]
@kwin @davidjgonzalez I'm getting similar limitations when I check/uncheck filters.

The page loads and I get my full set of results. I'll then check a filter and get a subset but when I uncheck it, it doesn't return to my fullset... It only displays 2 and the `p.limit` query param is set to 2.

Is it possible that something else is actually limiting the results to 2 once I uncheck everything and because only 2 results are returned the `p.limit` query param is set to 2? That would imply that the `p.limit` query param is automatically set to the number of results returned but I can't see why that would be...?

It seems like a similar situation as @kwin had above where `p.offset=0&p.limit=0` was added to the url...

**Comment by davidjgonzalez** [comment]
Can you update to 3.5.0 .. my PR supporting initial values in the query had some problems - I believe 3.5.0 takes care of all the permutations (atleast the ones I can think of)

**Comment by DigiLiviu** [comment]
Ok thanks for the response there @davidjgonzalez. I had actually fixed it by rolling back to 3.2.2. Will upgrade.

**Comment by davidjgonzalez** [comment]
Let me know if you still see anything off in 3.5.0! Thanks and sorry about that

**Comment by DigiLiviu** [comment]
@davidjgonzalez sorry about the delay here, the client has elected to stay on 3.2.2 until we have to move forward. Will update you if we have any issues with 3.5.0 when we do update.
