### ISSUE TITLE
Guess Total In asset share commons search results

### ISSUE THREAD

**Issue by abburiakil** [adobe/asset-share-commons#794]
Hi Team,
We have Use case for guess total in search results page-Guess total.  
The Guess Total Count is Coming as 2000+ if there are more than 2000 results for a search as the maximum limit of asset share commons is 2000 only. In our case we need to extend the guess total to get the exact value.

Any guidance/help will be appreciated. Thanks in advance!

**Comment by davidjgonzalez** [comment]
What limit do you need? The problem is as the limit is relaxed, it will eventually result in system degradation. 

Also, curious, what is the use case for knowing if they're are 1000 (the max limit) or 1001 results? What is the user going to do with that info? Once you get into the 100s and 1000s the usefulness starts of exact counts becomes dubious

**Comment by abburiakil** [comment]
Hi David,
Thanks for the response.
We have a need to display the total assets available and We need max limit to be extended to 5000, is there any way we can get the exact count for the search results?

**Comment by davidjgonzalez** [comment]
@abburiakil what happens when you have 6000 assets, will this # have to be increased again? At what point will you stop needing to increase it?

The max limit is currently hard-coded to prevent people from creating putting in a high guessTotal and causing themselves performance issues. What exactly are you going to do w/ the exact count thats in the 1000s -- ie whats the business requirement? Maybe we can solve the business problem in a different, safer way?

**Comment by SmritiMahto** [comment]
Hi David,
The Business use case is to fetch the search results count on runtime. If suppose the user searches for mov and the mov mime type assets are 3045 and mp4 as 8k the search results count should be displayed based on that. As now the guess total count is displayed as 2000+ or 1000+ the end users are unable to figure out how many exact total number of assets are there.
Is there any ways we can implement or ASC can help.

thanks,
Smriti Mahto

**Comment by SmritiMahto** [comment]
Hi David,
Any update on the Business use case.

Thanks,
Smriti Mahto

**Comment by davidjgonzalez** [comment]
Hi @SmritiMahto Displaying an exact number in itself isn't a business case -- the business case is what someone is doing/deciding based on that number.  

You state: 

> total count is displayed as 2000+ or 1000+ the end users are unable to figure out how many exact total number of assets are there.

...but don't explain what the end user is going to do with that exact number, and why they can't do it knowning there are over 1,000 results.

Also, I checked w/ the AEM product team stated the safe max guessTotal is 1000, so we wont want to exceed that guidance.
