### ISSUE TITLE
Enable Web-optimized image delivery on Card and List View of Search Results Component

### ISSUE THREAD

**Issue by shubhanshu23** [adobe/asset-share-commons#947]
Hi Folks, I am happy to contribute to this, Please see below

**Is your feature request related to a problem? Please describe.**
This is an enhancement/feature request. The current implementation of card and list view for Search Results relies on fetching image using [asset.rendition servlet.](https://github.com/adobe/asset-share-commons/blob/develop/core/src/main/java/com/adobe/aem/commons/assetshare/content/renditions/impl/AssetRenditionServlet.java). The images rendered are not fully web-optimized and leads to longer page load time and relatively lower lighthouse score.

**Describe the solution you'd like**
Utilize the [ AssetDelivery API](https://javadoc.io/doc/com.adobe.aem/aem-sdk-api/latest/com/adobe/cq/wcm/spi/AssetDelivery.html) to enable the use of the web-optimized **webp** image renditions are used in these components on Cloud Services.

**Describe alternatives you've considered**
Not specifically, but Fallback to AssetRenditon Servlet is the next best option.

**Additional context**
![image](https://github.com/adobe/asset-share-commons/assets/8725885/9335f5f0-422e-461a-905c-3f1eabf34fc8)

Resources: 

- https://experienceleague.adobe.com/docs/experience-manager-learn/cloud-service/developing/advanced/web-optimized-image-delivery-java-apis.html
- https://experienceleague.adobe.com/docs/experience-manager-core-components/using/developing/web-optimized-image-delivery.html?lang=en

**Comment by davidjgonzalez** [comment]
This is already in latest version

**Comment by shubhanshu23** [comment]
Great! I couldn't find it in the documentation of Search Results component or Renditions. Its available in the changelog. Thanks @davidjgonzalez

**Comment by davidjgonzalez** [comment]
@shubhanshu23 i did notice when deploying to AEM CS RDE, that the old SearchResults OSGi config was hanging around if you had a prior version installed, so if youre using RDE and seeing PNGs still, either reset the RDE and only instal 2.6.0+ or just delete the old SearchResults OSGi config -- this wont happen on true AEM CS since the OSGi configs are setup from scratch on every deploy - to be honest, im not sure why RDE keeps the old ones around even when you do a full deploy of the ui.config (or all) packages - but it seems to. Just a heads up since this confused me for a solid 15 mins :) 

`
$ aio aem:rde:status
$ aio aem:rde:delete com.adobe.aem.commons.assetshare.content.renditions.impl.dispatchers.InternalRedirectRenditionDispatcherImpl~SearchResults`
