### ISSUE TITLE
'Active filter' in property filter setting doesn't work

### ISSUE THREAD

**Issue by Sage-SA** [adobe/asset-share-commons#976]
Hi,
I need to pre-select a filter on a page so that by default, the selected filter is applied to the search results. I tried achieving this by checking the 'Active' box in the property filter setting, but the filter is not being applied and the page loads all the assets.
Can you please help me if there is any additional configuration I have to do.

Thanks,
Sara
![Property filter](https://github.com/adobe/asset-share-commons/assets/135127849/29217869-780f-4389-b7ee-e9da105b65ff)

**Comment by davidjgonzalez** [comment]
@Sage-SA  right you are ... im suprised we never noticed this before!

 I think this is going to turn out to be pretty tough to implement ... since well have to now have to crawl the page server side (when no parameters are provided) and create Java QB predicates. 

How necessary is this feature? Based on the level of effort to do this (and do it generically) im tempted to just remove the "Active" checkbox :)

**Comment by Sage-SA** [comment]
I understand your concerns about the implementation challenges. However, I believe having this feature work would be very beneficial as currently it's taking us a long time creating various search queries for each page and linking them manually.

**Comment by davidjgonzalez** [comment]
@Sage-SA refreshing my memory - it looks like Property and Path filters are the 2 components that support "Active" (default) selections - that sound right to you based on your use case?

**Comment by davidjgonzalez** [comment]
Please upgrade to https://github.com/adobe/asset-share-commons/releases/tag/asset-share-commons-3.4.0
